import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/button/Button';
import Navbar from '../layout/navbar/Navbar';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title> {"Lekan's blog"} </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<>
				<Navbar />
			</>
		</div>
	);
};

export default Home
